in this notebook we're going to cover some of the most fundamental
concepts of tensors using tensorflow

we're going to cover
* intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & numpy
* Using @tf.function (a way to speed up your regular python funcs)
* Using GPUs with tensorflow(or TPU)
* Exercises

 intro to tensors

In [1]:
import tensorflow as tf

print(tf.__version__)

2.6.0


In [2]:
#Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of a tensor(ndim stands for number of dimensions)

scalar.ndim

0

In [4]:
# create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
#check the dimension of the vector

vector.ndim

1

In [6]:
#create a matrix(has more than 1 dim)

matrix = tf.constant([[10, 7],
          [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
#create another matrix 
another_matrix = tf.constant([[10., 7],
                               [3., 2],
                               [8., 9.]], dtype = tf.float16)
    #specify the datatype with dtype parameter

In [9]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# what's the number of dimensions of another matrix

another_matrix.ndim

2

In [11]:
#let's create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
tensor.ndim

3

In [13]:
# we can also create tensors using tf.Variable
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [15]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [16]:
# let's try change one of the elements in changeable tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
# let's try change one of the elements in unchangeable tensor

unchangeable_tensor[0].assign(7)
# in tf.constant we cannot change we will get error.
#Only in tf.Variable we can make changes

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🗝️Note: Rarely in practice will you need to decide whether to use 
tf.constant or tf.Variable to create tensors, as tensorflow does this for you. However, if in doubt , use tf.constant and change it later if needed.

Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [18]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

-->The term "seed" is an abbreviation of the standard term "random seed". TensorFlow operators that produce random results accept an optional seed parameter. If you pass the same number to two instances of the same operator, they will produce the same sequence of results.

-->The tf.random.Generator class is used in cases where you want each RNG call to produce different results. It maintains an internal state (managed by a tf.Variable object) which will be updated every time random numbers are generated. Because the state is managed by tf.Variable, it enjoys all facilities provided by tf.Variable such as easy checkpointing, automatic control-dependency and thread safety.

You can get a tf.random.Generator by manually creating an object of the class or call tf.random.get_global_generator() to get the default global generator:

In [19]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
#Are they equal?
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)